config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    root 'tasks#index'
    resources :tasks do
      resources :taskuseranswers
      resources :ratings
    end
    resources :tags, only: [:show]
    get "search", to: "search#search"
  end
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings
  has_many :answerings, :dependent => :destroy
  has_many :answers, through: :answerings 
  belongs_to :topic
  belongs_to :user
  has_many_attached :avatar
  has_many :taskuseranswers, :dependent => :destroy
  has_many :ratings, :dependent => :destroy

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  searchkick

  mappings do
    indexes :name,  analyzer: 'english'
    indexes :condition,  analyzer: 'english'
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name', 'condition']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            name: {},
            condition: {},
          }
        }
      }
    )
  end

  def all_answers
    self.answers.map(&:name).join(',')
  end

  def all_answers=(names)
    self.answers = names.split(',').map do |name|
      Answer.where(name: name.strip).first_or_create!
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index,]
  before_action :set_task, only: [:show, :edit, :update]
  before_action :fetch_tags, only: %i[new edit]
  
  def index
    @tasks = Task.order("created_at DESC")
    @q = Task.ransack(params[:q])
    if @q
      @tasks = @q.result(distinct: true)
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id]).destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :topic_name,:condition, :all_answers, :topic_id, :avatar => [], :tag_ids => [])
  end

  def fetch_tags
    @tags = Tag.all
  end

end

app/helpers/task_helper.rb
module TaskHelper

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end

  def avg_rating(task_id)
    @rating = Rating.where(task_id: task_id)
    @sum = 0
    @rating.each do |t|
      @sum += t.star
    end
    if @rating.size != 0
      @avg = @sum / @rating.size
      Task.find(id = task_id).update(avgrait: @avg)
      return @avg.round
    else return 0
    end
  end

end

app/views/tasks/_flash.html.erb
<div class="row">
      <div class="col-md-12">
        <% flash.each do |name, message| %>
          <div class="alert alert-<%= name %>">
            <%= message %>
          </div>
        <% end %>
      </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task, tags: @tags do |f| %>
  <div class = "form-group">
    <%= f.label (t ".name"), class: "label" %>
    <%= f.text_field :name, class: "form-control", placeholder: (t ".plho_name") %>
  </div>
<div class = "form-group">
     <%= f.label (t ".answers"), class: "label" %>
     <%= f.text_field :all_answers, class: 'form-control', placeholder: (t ".plho_answers") %>
  </div>
  <div class = "form-group">
    <%= f.label (t ".tags"), class: "label" %>
    <%= f.collection_select :tag_ids, @tags, :id, :name, {}, multiple: true, class: 'js-multiple-select w-100' %>
  </div>

  <div class = "form-group">
    <%= f.label (t ".topic"), class: "label" %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :name, {:multiple => true}, class: "form-control") %>
  </div>

  <div class="field">
    <%= f.label (t ".gallery"), class: "label" %> <br>
    <%= f.file_field :avatar, multiple: true %>
  </div>

  <div class = "form-group">
    <%= f.label (t ".description"), class: "label" %>
    <div class="form-condition">
    <%= f.text_area :condition, style: "width: 100%; font-size:16px;", rows: 8, maxlength: 400, placeholder: (t ".plho_description") %>
    </div>
  </div>
  <div class = "form-group">
    <%= f.submit (t '.button_save'), class: 'btn btn-outline-primary pull-xxl-right mt-2' %>
    <%= link_to (t ".button_back"), :back, class: "btn btn-outline-primary pull-xxl-right mt-2" %> 
  </div>
<% end %>

app/views/tasks/_showtask.html.erb
<article class="task">
<section class="task-head">
<%= raw @task.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: "task_tags"}.join(" ") %>
</section> 
</article>
<% if current_user && @task.user_id == current_user.id%>
<div class='task_answers'> <%= t ".title_answers" %> <%= raw @task.answers.map(&:name).join(" , ") %> </div>
<% end %>
<div class="row mt-2">
    <div class="col-md-12">
      <h2>
        <h2> <%= t ".title_topic" %>  <%= @task.topic.name %> </h2>
      </h2>
    </div>
    </div>
  <div>
  <% @task.avatar.each do |avatars| %>
    <%= image_tag(avatars, height: 150, width: 250) %>
  <% end %>
</div>
<h2 class="mt-2"><%= t ".title_description" %> </h2>
<p>
<%= markdown(@task.condition) %>
</p>

app/views/tasks/_star.html.erb
<div class="d-flex justify-content-center">
<% if user_signed_in? && @task.user.id != current_user.id %>
<%= form_with model: [@task, @task.ratings.build] do |f| %>
  <p>
    <div class="form-group " id="star">
    <%= f.submit (t ".star_add"), class: "btn btn-primary" %> 
  </div>
  <p>
  <script>
  var ready;
 ready = function(){$('#star').raty({
    size     : 25,
    starOff:  '<%= asset_path('star-off.png', size:"25x25") %>',
    starOn : '<%= asset_path('star-on.png', size:"25x25") %>',
    scoreName: 'ratings[star]',
    half: false,
  });
 }
 $(document).ready(ready);
  $(document).on('page:load', ready);
  </script> 
<% end %> 
<% end %>
</div>

app/views/tasks/_tagcloud.erb
    <ul class="list-group list-group-horizontal-lg">
 <% tag_cloud(Tag.counts, %w{XS S M L XL}) do |tag, css_class| %>
        <li class="list-group-item"> <%= link_to tag.name, tag_path(tag.name), class: css_class %> </li>
      <% end %> 
      </ul>

app/views/tasks/_useranswer.html.erb
<% @c=0 %>
 <% @task.answers.each do |answer| %>
      <% @task.taskuseranswers.each do |uanswer| %>
    <% if answer.name == uanswer.name && user_signed_in? && current_user.id == uanswer.user_id %>
      <div style="background-color:green; text-align:center; padding: 5px; color:#fff; margin-top:50px">  <h3> Complete </h3> </div>
      <div class="d-flex justify-content-center">
            <%= render "star" %>
          </div>  
      <% @c+=1 %>
    <% end %>
    <% end %>
  <% end %>
<% if current_user && current_user.id != @task.user.id && @c<1 %>
<%= form_with model: [ @task, @task.taskuseranswers.build ] do |form| %>
  <p>
    <%= form.label "Answer" %><br>
    <%= form.text_field :name %> 
    <%= form.submit 'add', :class => 'btn btn-primary'%>
  </p>
<% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1> <%= t ".title" %> </h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<%= render 'tagcloud' %>
  <div class="row mt-2">
    <div class="col-md-4">
      <h1> <%= t '.title' %> </h1>
    </div>
    <div class="col-md-4 ms-auto">
      <div class="d-flex justify-content-end">
        <%= link_to ( t '.button_add_task') , new_task_path, class: 'btn btn-primary me-1' %>
        <div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= t ".sort" %>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li>
    <a class="dropdown-item" href="#">
        <%= sort_link(@q, :created_at) do %>
            <strong><%= t ".sort_date" %></strong>
        <% end %>
    </a>
    </li>
    <li>
    <a class="dropdown-item" href="#">
        <%= sort_link(@q, :avgrait) do %>
            <strong><%= t ".sort_rating" %></strong>
        <% end %>
      </a>
    </li>
  </ul>
</div>
      </div>
    </div>
  </div>
  <% @tasks.each do |task| %>
    <div class="card mt-3">
    <div class="card-body">
    <article class="task">
      <section class="task-head">
          <%= raw task.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: "task_tags" }.join(" ") %>
      </section>
  <section class=" task-body">
  <div class="cart-title">
          <div class="row mt-2">
            <div class="col-md-11">
              <%= link_to task.name, task_path(task.id), class: "task_name" %>
            </div>
            <div class="col-md-1 ms-auto">
              <div class="d-flex justify-content-end">
                  <div class="avg_rating"><%= avg_rating(task.id) %> </div>
                  <%= image_tag("Star/star-on.png",size: "30x30")%>
              </div>
            </div>
          </div>
          </div>
      </section>
    </article>
        </div>
</div>
    <% end %>

app/views/tasks/new.html.erb
<h1> <%= t ".title" %> <h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<%= render 'flash' %>
  <div class="row mt-2">
    <div class="col-md-11">
      <h2>
        <%= @task.name %>
      </h2>
    </div>
    <div class="col-md-1 d-flex justify-content-end mb-2">
           <div class="show_rating">
          <div class="show_avg_rating"> <%= avg_rating(@task.id) %> </div>
          <%= image_tag("Star/star-on.png",size: "30x30")%>
        </div>
        </div>
          </div>
        <div class="btn-toolbar text-center d-block mx-auto">
        <%= link_to (t ".button_add_task") , new_task_path, class: 'btn btn-primary mt-1 btn-block' %>
        <% if current_user && @task.user_id==current_user.id %>
            <%= link_to (t ".button_change") , edit_task_path, class: 'btn btn-primary mt-1 btn-block' %>
             <%= link_to (t ".button_delete") , task_path, data: {confirm: 'You are really?' }, class: 'btn btn-primary mt-1 btn-block' , method:
            :delete %>
              <% end %>
                </div>
                
  <%= render 'showtask' %>
  
    <%= render 'useranswer' %>
    <%= link_to (t ".button_back"), :back, class: "btn btn-outline-primary pull-xxl-right mt-2" %>